// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: websocket/msg/messages.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WSMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSMessage) Reset() {
	*x = WSMessage{}
	mi := &file_websocket_msg_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSMessage) ProtoMessage() {}

func (x *WSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_msg_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSMessage.ProtoReflect.Descriptor instead.
func (*WSMessage) Descriptor() ([]byte, []int) {
	return file_websocket_msg_messages_proto_rawDescGZIP(), []int{0}
}

func (x *WSMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WSMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_websocket_msg_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_msg_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_websocket_msg_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Auth) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Auth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type WSError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSError) Reset() {
	*x = WSError{}
	mi := &file_websocket_msg_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSError) ProtoMessage() {}

func (x *WSError) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_msg_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSError.ProtoReflect.Descriptor instead.
func (*WSError) Descriptor() ([]byte, []int) {
	return file_websocket_msg_messages_proto_rawDescGZIP(), []int{2}
}

func (x *WSError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_websocket_msg_messages_proto protoreflect.FileDescriptor

const file_websocket_msg_messages_proto_rawDesc = "" +
	"\n" +
	"\x1cwebsocket/msg/messages.proto\x12\x03msg\"9\n" +
	"\tWSMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"5\n" +
	"\x04Auth\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x1f\n" +
	"\aWSError\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05errorB\x11Z\x0f./websocket;msgb\x06proto3"

var (
	file_websocket_msg_messages_proto_rawDescOnce sync.Once
	file_websocket_msg_messages_proto_rawDescData []byte
)

func file_websocket_msg_messages_proto_rawDescGZIP() []byte {
	file_websocket_msg_messages_proto_rawDescOnce.Do(func() {
		file_websocket_msg_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_websocket_msg_messages_proto_rawDesc), len(file_websocket_msg_messages_proto_rawDesc)))
	})
	return file_websocket_msg_messages_proto_rawDescData
}

var file_websocket_msg_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_websocket_msg_messages_proto_goTypes = []any{
	(*WSMessage)(nil), // 0: msg.WSMessage
	(*Auth)(nil),      // 1: msg.Auth
	(*WSError)(nil),   // 2: msg.WSError
}
var file_websocket_msg_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_websocket_msg_messages_proto_init() }
func file_websocket_msg_messages_proto_init() {
	if File_websocket_msg_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_websocket_msg_messages_proto_rawDesc), len(file_websocket_msg_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_websocket_msg_messages_proto_goTypes,
		DependencyIndexes: file_websocket_msg_messages_proto_depIdxs,
		MessageInfos:      file_websocket_msg_messages_proto_msgTypes,
	}.Build()
	File_websocket_msg_messages_proto = out.File
	file_websocket_msg_messages_proto_goTypes = nil
	file_websocket_msg_messages_proto_depIdxs = nil
}
